version: '3'

services:
  web:
    image: frontend
    build: ./frontend
    ports:
      - 80:80
    healthcheck:
      test: curl -sS http://127.0.0.1:80 || echo 1
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - frontend_network
      
  db:
    image: postgres:alpine3.14
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_network

  backend:
    image: backend
    build: ./lib_catalog
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    depends_on:
      - db
    healthcheck:
      test: curl -sS http://127.0.0.1:8000 || echo 1
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - backend_network

networks:
  frontend_network:
  backend_network: