version: "3.9"
   
services:
  db:
    image: postgres:alpine3.14
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  web:
    build: .
    # command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=django
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
    depends_on:
      - db
    healthcheck:
      test: curl -sS http://127.0.0.1:8000 || echo 1
      interval: 5s
      timeout: 10s
      retries: 3