# syntax=docker/dockerfile:1
FROM python:3.8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt

USER daemon
COPY . /app/

ENTRYPOINT ["/bin/sh", "/app/docker-entrypoint.sh"]